"""rename category

Revision ID: 901df21cadbe
Revises: 1a9ee3d09c91
Create Date: 2023-02-13 17:28:39.899226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901df21cadbe'
down_revision = '1a9ee3d09c91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
