"""rela

Revision ID: e589311fef68
Revises: 28cc5a5e50c2
Create Date: 2023-03-11 18:54:28.826667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e589311fef68'
down_revision = '28cc5a5e50c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
